spring.application.name=schoolMedical

#server
server.port=8080
server.servlet.context-path=/yte

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/db_medical
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Set timezone
spring.jackson.time-zone=Asia/Ho_Chi_Minh

# Send email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kiritohackiem05@gmail.com
spring.mail.password=rvidiyvfaqgzcuqb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
